# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

console_title_template: "{{.HostName}} -- {{.PWD}}"
blocks:
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
    leading_diamond: ╭─
    template: " {{ if .WSL }}WSL at {{ end }}{{.Icon}} "
    foreground: "#000000"
    background: "#d3d7cf"
    type: os
    style: diamond
  - properties:
      cache_duration: none
    template: "{{ if .SSHSession }}\ueba9 {{ .HostName }}{{ end }}"
    foreground: "#ffffff"
    powerline_symbol: 
    background: "#c386f1"
    type: session
    style: powerline
  - properties:
      cache_duration: none
      home_icon: "~"
      style: full
    template: " \uf07c {{ .Path }} "
    foreground: "#e4e4e4"
    powerline_symbol: 
    background: "#3465a4"
    type: path
    style: powerline
  - properties:
      branch_icon: "\uf126 "
      cache_duration: none
      fetch_stash_count: true
      fetch_status: true
      fetch_upstream_icon: true
    template: " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
    foreground: "#000000"
    powerline_symbol: 
    background: "#4e9a06"
    type: git
    style: powerline
    background_templates:
    - "{{ if or (.Working.Changed) (.Staging.Changed) }}#c4a000{{ end }}"
    - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}"
    - "{{ if gt .Ahead 0 }}#89d1dc{{ end }}"
    - "{{ if gt .Behind 0 }}#4e9a06{{ end }}"
  newline: true
- type: prompt
  alignment: right
  segments:
  - properties:
      cache_duration: none
      fetch_version: true
    template: " {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} \ue718 "
    foreground: "#ffffff"
    powerline_symbol: 
    background: "#689f63"
    type: node
    style: powerline
    invert_powerline: true
  - properties:
      cache_duration: none
      display_mode: files
      fetch_virtual_env: false
    template: " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} \ue235 "
    foreground: "#111111"
    powerline_symbol: 
    background: "#FFDE57"
    type: python
    style: powerline
    invert_powerline: true
  - properties:
      cache_duration: none
      display_default: false
    template: " {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} \ue7ad "
    foreground: "#ffffff"
    powerline_symbol: 
    type: aws
    style: powerline
    background_templates:
    - "{{if contains \"default\" .Profile}}#FFA400{{end}}"
    - "{{if contains \"jan\" .Profile}}#f1184c{{end}}"
    invert_powerline: true
  - properties:
      cache_duration: none
    template: " \uf0ad "
    foreground: "#111111"
    powerline_symbol: 
    background: "#ffff66"
    type: root
    style: powerline
    invert_powerline: true
  - properties:
      cache_duration: none
    template: " {{ .FormattedMs }} \uf252 "
    foreground: "#000000"
    powerline_symbol: 
    background: "#c4a000"
    type: executiontime
    style: powerline
    invert_powerline: true
  - properties:
      cache_duration: none
    leading_diamond: 
    trailing_diamond: ─╮
    template: " {{ .CurrentDate | date .Format }} \uf017 "
    foreground: "#000000"
    background: "#d3d7cf"
    type: time
    style: diamond
    invert_powerline: true
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
    template: ╰─
    foreground: "#d3d7cf"
    type: text
    style: plain
  - properties:
      always_enabled: true
      cache_duration: none
    template: "{{ if gt .Code 0 }} ✘ {{.Code}} ❯ {{ else }} <#4e9a06>✔</> ❯ {{ end }}"
    foreground: "#d3d7cf"
    type: status
    style: powerline
    background_templates:
    - "{{ if gt .Code 0 }}#cc2222{{ end }}"
    invert_powerline: true
  newline: true
- type: rprompt
  segments:
  - properties:
      cache_duration: none
    template: ─╯
    foreground: "#d3d7cf"
    type: text
    style: plain
version: 3
final_space: true
